---
# NOTE(awiddersheim): Gather facts for all hosts as a
# first step since several plays below require them when
# building their configurations. The below 'gather_facts'
# set to 'false' is a bit confusing but this is to avoid
# Ansible gathering facts twice.
- name: Gather facts for all hosts
  hosts: all
  gather_facts: false
  tasks:
    - setup:
    - ec2_facts:

- name: Deploy filebeat
  gather_facts: false
  hosts: all
  roles:
     - { role: geerlingguy.filebeat,
         when: enable_filebeat | bool }

- name: Deploy telegraf
  gather_facts: false
  hosts: all
  roles:
     - { role: rossmcdonald.telegraf,
         when: enable_telegraf | bool }
