---
# NOTE(awiddersheim): Gather facts for all hosts as a
# first step since several plays below require them when
# building their configurations. The below 'gather_facts'
# set to 'false' is a bit confusing but this is to avoid
# Ansible gathering facts twice.
- name: Gather facts for all hosts
  hosts: all
  gather_facts: false
  tasks:
    - setup:

- name: Setup chrony
  hosts: all
  gather_facts: false
  roles:
     - { role: influxdata.chrony,
         when: enable_chrony | bool }

- name: Setup docker and docker-compose
  hosts: all
  gather_facts: false
  roles:
     - { role: geerlingguy.docker,
         when: enable_docker | bool }
